//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARPARK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abone()
        {
            this.AboneOdeme = new HashSet<AboneOdeme>();
        }
    
        public int AboneID { get; set; }
        public string Adi { get; set; }
        public string Soyad { get; set; }
        public string TCNO { get; set; }
        public string CepTel { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> AracID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<int> YetkiID { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual KullaniciYetki KullaniciYetki { get; set; }
        public virtual Uye Uye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AboneOdeme> AboneOdeme { get; set; }
    }
}
