//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARPARK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public int AyarId { get; set; }
        public Nullable<int> ToplamKapasite { get; set; }
        public Nullable<int> OtomobilKapasite { get; set; }
        public Nullable<int> KamyonetKapasite { get; set; }
        public string ResimKlasorYolu { get; set; }
    }
}
