//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARPARK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gelirler
    {
        public int GelirID { get; set; }
        public string GelirTuru { get; set; }
        public System.DateTime OdemeTarihi { get; set; }
        public decimal Tutar { get; set; }
        public int AracID { get; set; }
    
        public virtual Arac Arac { get; set; }
    }
}
