//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARPARK.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TCNo { get; set; }
        public string Fotograf { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> UyeID { get; set; }
        public int YetkiID { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual KullaniciYetki KullaniciYetki { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
